"""
Sample claim scenarios used for demonstration in the Streamlit app,
matching the example test cases in the problem statement.
"""
from state import ClaimInput

SAMPLE_CLAIMS: dict[str, ClaimInput] = {
    "1. Complete claim, valid docs -> Auto Approve": {
        "claim_id": "CLM-1001",
        "policy_number": "POL-58291",
        "claimant_name": "Ananya Sharma",
        "policy_status": "active",
        "policy_expiry_date": "2027-01-01",
        "claim_type": "Health",
        "claim_amount": 45000.0,
        "policy_coverage_limit": 500000.0,
        "incident_date": "2026-06-01",
        "claim_filed_date": "2026-06-05",
        "submitted_documents": ["ID Proof", "Hospital Bill", "Discharge Summary", "Doctor Prescription"],
        "incident_description": "Patient was hospitalized for acute appendicitis and underwent surgery.",
        "claimant_claim_history_count": 0,
    },
    "2. Missing required documents -> Reject": {
        "claim_id": "CLM-1002",
        "policy_number": "POL-77123",
        "claimant_name": "Rohit Verma",
        "policy_status": "active",
        "policy_expiry_date": "2027-03-15",
        "claim_type": "Auto",
        "claim_amount": 30000.0,
        "policy_coverage_limit": 200000.0,
        "incident_date": "2026-05-10",
        "claim_filed_date": "2026-05-12",
        "submitted_documents": ["ID Proof", "Repair Estimate"],
        "incident_description": "Minor collision with another vehicle at a traffic signal.",
        "claimant_claim_history_count": 1,
    },
    "3. Suspicious claim amount -> Human Approval": {
        "claim_id": "CLM-1003",
        "policy_number": "POL-33456",
        "claimant_name": "Vikram Nair",
        "policy_status": "active",
        "policy_expiry_date": "2026-12-31",
        "claim_type": "Property",
        "claim_amount": 198000.0,
        "policy_coverage_limit": 200000.0,
        "incident_date": "2026-06-15",
        "claim_filed_date": "2026-06-16",
        "submitted_documents": ["ID Proof", "Ownership Proof", "Damage Photos", "Repair Estimate"],
        "incident_description": "Fire damage to kitchen and adjoining storage room.",
        "claimant_claim_history_count": 4,
    },
    "4. Expired policy -> Reject": {
        "claim_id": "CLM-1004",
        "policy_number": "POL-90812",
        "claimant_name": "Meera Iyer",
        "policy_status": "expired",
        "policy_expiry_date": "2026-01-01",
        "claim_type": "Health",
        "claim_amount": 20000.0,
        "policy_coverage_limit": 300000.0,
        "incident_date": "2026-05-20",
        "claim_filed_date": "2026-05-22",
        "submitted_documents": ["ID Proof", "Hospital Bill", "Discharge Summary", "Doctor Prescription"],
        "incident_description": "Treatment for viral fever and dehydration.",
        "claimant_claim_history_count": 0,
    },
    "5. High-value claim, valid docs -> Human Approval": {
        "claim_id": "CLM-1005",
        "policy_number": "POL-44789",
        "claimant_name": "Karan Malhotra",
        "policy_status": "active",
        "policy_expiry_date": "2027-08-01",
        "claim_type": "Life",
        "claim_amount": 750000.0,
        "policy_coverage_limit": 1000000.0,
        "incident_date": "2026-04-01",
        "claim_filed_date": "2026-04-10",
        "submitted_documents": ["ID Proof", "Death Certificate", "Policy Document", "Nominee ID Proof"],
        "incident_description": "Policyholder passed away due to cardiac arrest; nominee filing claim.",
        "claimant_claim_history_count": 0,
    },
}
